M48
; DRILL file KiCad 10.0.0 date 2026-04-05T00:29:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-05T00:29:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X129.397Y-78.769
X129.397Y-84.549
T2
X137.668Y-107.95
M30
